// <auto-generated />
namespace Edu.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatesidebarRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatesidebarRole));
        
        string IMigrationMetadata.Id
        {
            get { return "201812130144337_update-sidebarRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
